import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import MenuComponent from "@/components/menu-component/MenuComponent";



export const metadata: Metadata = {
    title: "Frame Flow",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
            { url: "favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
        ],
        apple: "favicon/apple-touch-icon.png",
    }
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <MenuComponent/>
        {children}
        </body>
        </html>
    );
}
